const data = [

  {
    category_name: "Noodles",
    name: "Veg Noodles",
    full_price: 99,
    veg: "true",
    description: "hello",
    img: "https://b.zmtcdn.com/data/dish_photos/e55/5fa13adc2d1b4df220797e7e2719de55.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Noodles",
    name: "Veg Schezwan Noodles",
    full_price: 119,
    veg: "true",
    description: "hello",
    img: "https://b.zmtcdn.com/data/dish_photos/06d/8c7b7e78712766f1ebf358465451206d.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Noodles",
    name: "Veg Singapuri Noodles",
    full_price: 119,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Veg Hakka Noodles",
    full_price: 139,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Butter Garlic Noodles",
    full_price: 129,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Paneer Garlic Noodles",
    full_price: 139,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Egg Noodles",
    full_price: 119,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Noodles",
    full_price: 139,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Chilli Noodles",
    full_price: 139,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Singapuri Noodles",
    full_price: 139,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Hakka Noodles",
    full_price: 139,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Garlic Noodles",
    full_price: 139,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Noodles",
    name: "Chicken Egg Noodles",
    full_price: 149,
    veg: "false",
    description: "hello",
  },




  {
    category_name: "Chinese",
    name: "Veg Manchurian",
    half_price: 149,
    full_price: 159,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Paneer Chilli",
    half_price: 159,
    full_price: 169,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Mashroom Chilli",
    half_price: 159,
    full_price: 169,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Paneer Manchurian",
    half_price: 159,
    full_price: 169,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Paneer Mashroom Chilli",
    half_price: 169,
    full_price: 179,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Chicken 65",
    half_price: 110,
    full_price: 199,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Chicken Chilli",
    half_price: 110,
    full_price: 199,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese",
    name: "Chicken Manchuian",
    half_price: 110,
    full_price: 199,
    half_qty: "Dry",
    full_qty: "Gravy",
    veg: "true",
    description: "hello",
  },

  {
    category_name: "Chinese",
    name: "Chicken ",
    half_price: 110,
    full_price: 199,
    half_qty: "Lollipop",
    full_qty: "Drums",
    veg: "true",
    description: "hello",
  },




  {
    category_name: "Biryani",
    name: "Veg Biryani",
    full_price: 139,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Veg Dum Biryani",
    full_price: 149,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Veg Lucknowi Biryani",
    full_price: 149,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Veg Hyderabadi Biryani",
    full_price: 149,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Paneer Tikka Biryani",
    full_price: 169,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Egg Biryani",
    full_price: 169,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Biryani",
    full_price: 189,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Tikka Dum Biryani",
    full_price: 189,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Lucknowi Biryani",
    full_price: 189,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Hyderabadi Biryani",
    full_price: 189,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Egg Biryani",
    full_price: 199,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Biryani",
    name: "Chicken Leg Biryani [2 Leg Pieces]",
    full_price: 249,
    veg: "false",
    description: "hello",
  },






  {
    category_name: "Rice",
    name: "Veg Fried Rice",
    full_price: 129,
    veg: "true",
    description: "Stir fried rice with mixed vegetable and seasoning, a popular Indo Chinese dish.",
    img: "https://b.zmtcdn.com/data/dish_photos/75a/2e574d8c53efd371b5d4dbc8279a175a.jpg?fit=around|130:130&crop=130:130;*,*",
  },
  {
    category_name: "Rice",
    name: "Veg Fried Jeera Rice",
    full_price: 129,
    veg: "true",
    description: "Stir fried rice with mixed vegetable and seasoning, a popular Indo Chinese dish.",
    img: "https://b.zmtcdn.com/data/dish_photos/75a/2e574d8c53efd371b5d4dbc8279a175a.jpg?fit=around|130:130&crop=130:130;*,*",
  },
  {
    category_name: "Rice",
    name: "Veg Schezwan Rice",
    full_price: 129,
    veg: "true",
    description: "A spicy and tangy veg rice dish, loaded with veggies and tossed in fiery schezwan sauce. A popular Indo Chinese favorite.",
    img: "https://b.zmtcdn.com/data/dish_photos/20c/a744f47dbb7fa1f043074a2f7a9ef20c.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Rice",
    name: "Butter Garlic Rice",
    full_price: 139,
    veg: "true",
    description: "A fragrant and flavorful rice dish, infused with the richness of butter and the sharpness of garlic.",
    img: "https://b.zmtcdn.com/data/dish_photos/826/550ef01c3084544087ee3a137def5826.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Rice",
    name: "Paneer Garlic Rice",
    full_price: 149,
    veg: "true",
    description: "A fusion dish of Indian and Chinese cuisines, made with rice, paneer and vegetables stir fried with spices.",
  },
  {
    category_name: "Rice",
    name: "Egg Fried Rice",
    full_price: 129,
    veg: "false",
    description: "Stir fried rice cooked with scrambled eggs and veggies, a classic and simple Chinese dish.",
  },
  {
    category_name: "Rice",
    name: "Chicken Garlic Rice",
    full_price: 149,
    veg: "false",
    description: "Tender chicken pieces and fragrant garlic infused in stir fried rice, a savory meal.",
    img: "https://b.zmtcdn.com/data/dish_photos/40f/751f6c4233290427a4e6107b5061940f.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Rice",
    name: "Chicken Egg Fried Rice",
    full_price: 159,
    veg: "false",
    description: "A classic Chinese dish, made with scrambled egg, tender chicken pieces, and stir fried rice. Satisfying and delicious.",
    img: "https://b.zmtcdn.com/data/dish_photos/753/68bcba9cfecd80fa42078a71226ef753.jpg?fit=around|130:130&crop=130:130;*,*"
  },



  

  {
    category_name: "Indian",
    name: "Mix. Veg",
    full_price: 169,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Paneer Butter Masala",
    full_price: 199,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Paneer Kadahi",
    full_price: 219,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Paneer Handi",
    full_price: 219,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Paneer Do Pyaza",
    full_price: 219,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Mushroom Kadahi",
    full_price: 249,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Mushroom Do Pyaza",
    full_price: 249,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Mushroom Handi",
    full_price: 249,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Chicken Kadahi",
    full_price: 279,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Chicken Handi",
    full_price: 279,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Chicken Do Pyaza",
    full_price: 279,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian",
    name: "Chicken Dehati",
    full_price: 279,
    veg: "false",
    description: "hello",
  },





  {
    category_name: "Rolls",
    name: "Veg Roll",
    full_price: 49,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Veg Manchurian Roll",
    full_price: 70,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Paneer Roll",
    full_price: 70,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Paneer 65 Roll",
    full_price: 75,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Paneer Manchurian Roll",
    full_price: 75,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Egg Roll",
    full_price: 70,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Chicken Roll",
    full_price: 80,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Chicken Manchurian Roll",
    full_price: 85,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Chicken 65 Roll",
    full_price: 85,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Rolls",
    name: "Chicken Egg Roll",
    full_price: 90,
    veg: "false",
    description: "hello",
  },






  {
    category_name: "Soup",
    name: "Veg Hot and Soup",
    full_price: 90,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Veg Corn Soup",
    full_price: 100,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Veg Manchow Soup",
    full_price: 105,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Tomato Soup",
    full_price: 90,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Mashroom Soup",
    full_price: 120,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Chicken Hot and Soup",
    full_price: 130,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Chicken Manchow Soup",
    full_price: 140,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Soup",
    name: "Meal Heaven Special Chicken Soup",
    full_price: 160,
    veg: "false",
    description: "hello",
  },
  





  {
    category_name: "Momos",
    name: "Veg Momos Steam",
    full_price: 70,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Veg Momos Fry",
    full_price: 90,
    veg: "true",
    description: "hello",
  },

  {
    category_name: "Momos",
    name: "Veg Momos Chilli",
    full_price: 99,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Veg Momos Kurkuri",
    full_price: 99,
    veg: "true",
    description: "hello",
  },



  {
    category_name: "Momos",
    name: "Paneer Momos Steam",
    full_price: 90,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Paneer Momos Fry",
    full_price: 110,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Paneer Momos Chilli",
    full_price: 109,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Paneer Momos Kurkuri",
    full_price: 109,
    veg: "true",
    description: "hello",
  },



  {
    category_name: "Momos",
    name: "Chicken Momos Steam",
    full_price: 99,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Chicken Momos Fry",
    full_price: 110,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Chicken Momos Chilli",
    full_price: 119,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Momos",
    name: "Chicken Momos Fry",
    full_price: 119,
    veg: "false",
    description: "hello",
  },






  {
    category_name: "Quick Meal",
    name: "Boiled Egg [2 Pieces]",
    full_price: 49,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Steamed Corn",
    full_price: 99,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Sandwich",
    half_price: 59,
    full_price: 79,
    half_qty: "Veg",
    full_qty: "Paneer",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Chicken Sandwich",
    full_price: 99,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Burger",
    half_price: 59,
    full_price: 79,
    half_qty: "Aloo",
    full_qty: "Paneer",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Chicken Burger",
    full_price: 99,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Pizza",
    half_price: 149,
    full_price: 179,
    half_qty: "Veg",
    full_qty: "Paneer",
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Quick Meal",
    name: "Chicken Pizza",
    full_price: 199,
    veg: "false",
    description: "hello",
  },





  {
    category_name: "Drinks",
    name: "Vanilla Shake",
    full_price: 139,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Chocalate Shake",
    full_price: 139,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Strawberry Shake",
    full_price: 139,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Chocalate Kit-Kat Shake",
    full_price: 149,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Chocalate Oreo Shake",
    full_price: 149,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Chocalate Hazelnut Shake",
    full_price: 159,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Belgiam Choclate Shake",
    full_price: 179,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Mint Virgin Mojito",
    full_price: 109,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Lemon Soda",
    full_price: 99,
    description: "hello",
  },
  {
    category_name: "Drinks",
    name: "Masala Soda",
    full_price: 99,
    description: "hello",
  },









  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561389947,
    name: "Veg Basic wali Thali",
    full_price: 199.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561389946,
    name: "Veg Special wali Thali",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561392624,
    name: "Mushroom wali Veg Special Thali",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561390680,
    name: "Veg Badshaho wali Thali",
    full_price: 329.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Thali",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561394704,
    name: "Thali Basic Wali [Serves 1]",
    full_price: 229.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561395025,
    name: "Thali Special Wali",
    full_price: 329.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561395400,
    name: "Deluxe Thali",
    full_price: 379.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393412,
    name: "Chinese Basic Thali",
    full_price: 199.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393413,
    name: "Chinese Special Thali",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393414,
    name: "Chinese Deluxe Thali",
    full_price: 329.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394264,
    name: "Basic Chinese Thali",
    full_price: 229.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394265,
    name: "Special Chinese Thali",
    full_price: 299.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394424,
    name: "Deluxe Chinese Thali",
    full_price: 349.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Veg Maggi",
    catalogue_id: 534225049,
    name: "Vegetable Maggi",
    full_price: 199.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Veg Maggi",
    catalogue_id: 534225065,
    name: "Veg Cheese Maggi",
    full_price: 219.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Non Veg Maggi",
    catalogue_id: 534225692,
    name: "Egg Maggi",
    full_price: 219.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Non Veg Maggi",
    catalogue_id: 534225693,
    name: "Chicken Maggi",
    full_price: 249.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448009,
    name: "Paneer Chilli Gravy",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448021,
    name: "Mushroom Chilli Gravy",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448032,
    name: "Veg Manchurian Gravy",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448023,
    name: "Chicken Chilli Gravy",
    full_price: 269.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448013,
    name: "Chicken 65 Gravy",
    full_price: 289.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448025,
    name: "Chicken Manchurian Gravy",
    full_price: 289.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315246,
    name: "Aloo Matar",
    full_price: 199.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315427,
    name: "Aloo Gobhi",
    full_price: 199.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315426,
    name: "Mix Veg",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315037,
    name: "Matar Mushroom",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 531448008,
    name: "Paneer Kadahi Gravy",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 531448065,
    name: "Paneer Butter Masala",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314940,
    name: "Matar Paneer",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314941,
    name: "Shahi Paneer",
    full_price: 299.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314942,
    name: "Paneer Do Pyaza",
    full_price: 299.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315035,
    name: "Mushroom Butter Masala",
    full_price: 299.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315036,
    name: "Mushroom Masala Gravy",
    full_price: 299.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531447998,
    name: "Kadahi Chicken",
    full_price: 299.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531448022,
    name: "Chicken Dehati",
    full_price: 299.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531448061,
    name: "Chicken Handi",
    full_price: 299.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 550314872,
    name: "Chicken Do Pyaza",
    full_price: 349.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 550314873,
    name: "Butter Chicken",
    full_price: 349.0,
    veg: "false",
    description: "hello",
  },
  
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531447997,
    name: "Paneer Chilli Dry",
    full_price: 259.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448001,
    name: "Paneer 65 Dry",
    full_price: 259.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448024,
    name: "Manchurian Dry",
    full_price: 259.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448020,
    name: "Mushroom Chilli Dry",
    full_price: 269.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531448012,
    name: "Chicken 65 Dry",
    full_price: 269.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531448064,
    name: "Chicken Chilli Dry",
    full_price: 269.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531447999,
    name: "Chicken Manchurian Dry",
    full_price: 279.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 538402178,
    name: "Chicken Lollipop",
    full_price: 349.0,
    veg: "false",
    description: "hello",
  },
  
  





  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480560,
    name: "Veg Noodles + Veg Manchurian",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480561,
    name: "Chicken Noodles + Veg Manchurian",
    full_price: 279.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480562,
    name: "Chicken Noodles + Chicken Manchurian",
    full_price: 329.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479950,
    name: "Veg Fried Rice + Veg Manchurian",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479951,
    name: "Chicken Fried Rice + Veg Manchurian",
    full_price: 279.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479952,
    name: "Chicken Fried Rice + Chicken Manchurian",
    full_price: 329.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 531448060,
    name: "Biryani Combo",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 531447996,
    name: "Momos Combo",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Noodles Combo",
    catalogue_id: 531448016,
    name: "Paneer Chilli",
    full_price: 249.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Combos",
    subcategory_name: "Noodles Combo",
    catalogue_id: 531448016,
    name: "Chicken Chilli",
    full_price: 269.0,
    veg: "false",
    description: "hello",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892085,
    name: "5 Tawa Roti",
    full_price: 85.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892086,
    name: "2 Lachha Paratha",
    full_price: 80.0,
    veg: "true",
    description: "hello",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892087,
    name: "5 Tawa Roti with Butter",
    full_price: 110.0,
    veg: "true",
    description: "hello",
  },
  
  

  {
    category_name: "Desserts",
    subcategory_name: "Desserts",
    catalogue_id: 544109219,
    name: "Gulab Jamun (2 Pcs)",
    full_price: 100.0,
    veg: "true",
    description: "hello",
  },
];

export default data;
