const data = [
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448011,
    catalogue_name: "Veg Fried Rice",
    full_price: 199.0,
    veg: "true",
    description: "Stir fried rice with mixed vegetable and seasoning, a popular Indo Chinese dish.",
    img: "https://b.zmtcdn.com/data/dish_photos/75a/2e574d8c53efd371b5d4dbc8279a175a.jpg?fit=around|130:130&crop=130:130;*,*",
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448057,
    catalogue_name: "Veg Schezwan Fried Rice",
    full_price: 199.0,
    veg: "true",
    description: "A spicy and tangy veg rice dish, loaded with veggies and tossed in fiery schezwan sauce. A popular Indo Chinese favorite.",
    img: "https://b.zmtcdn.com/data/dish_photos/20c/a744f47dbb7fa1f043074a2f7a9ef20c.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448005,
    catalogue_name: "Butter Garlic Fried Rice",
    full_price: 219.0,
    veg: "true",
    description: "A fragrant and flavorful rice dish, infused with the richness of butter and the sharpness of garlic.",
    img: "https://b.zmtcdn.com/data/dish_photos/826/550ef01c3084544087ee3a137def5826.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448034,
    catalogue_name: "Paneer Garlic Fried Rice",
    full_price: 229.0,
    veg: "true",
    description: "A fusion dish of Indian and Chinese cuisines, made with rice, paneer and vegetables stir fried with spices.",
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448062,
    catalogue_name: "Egg Fried Rice",
    full_price: 219.0,
    veg: "false",
    description: "Stir fried rice cooked with scrambled eggs and veggies, a classic and simple Chinese dish.",
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448058,
    catalogue_name: "Chicken Egg Fried Rice",
    full_price: 249.0,
    veg: "false",
    description: "A classic Chinese dish, made with scrambled egg, tender chicken pieces, and stir fried rice. Satisfying and delicious.",
    img: "https://b.zmtcdn.com/data/dish_photos/753/68bcba9cfecd80fa42078a71226ef753.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Fried Rice",
    subcategory_name: "Fried Rice",
    catalogue_id: 531448002,
    catalogue_name: "Chicken Garlic Rice",
    full_price: 249.0,
    veg: "false",
    description: "Tender chicken pieces and fragrant garlic infused in stir fried rice, a savory meal.",
    img: "https://b.zmtcdn.com/data/dish_photos/40f/751f6c4233290427a4e6107b5061940f.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448035,
    catalogue_name: "Veg Noodles",
    full_price: 199.0,
    veg: "true",
    img: "https://b.zmtcdn.com/data/dish_photos/e55/5fa13adc2d1b4df220797e7e2719de55.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448003,
    catalogue_name: "Veg Schezwan Noodles",
    full_price: 199.0,
    veg: "true",
    img: "https://b.zmtcdn.com/data/dish_photos/06d/8c7b7e78712766f1ebf358465451206d.jpg?fit=around|130:130&crop=130:130;*,*"
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448038,
    catalogue_name: "Butter Garlic Noodles",
    full_price: 219.0,
    veg: "true",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448050,
    catalogue_name: "Paneer Garlic Noodles",
    full_price: 229.0,
    veg: "true",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448051,
    catalogue_name: "Veg Hakka Noodles",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448059,
    catalogue_name: "Veg Singapuri Noodles",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448052,
    catalogue_name: "Egg Noodles",
    full_price: 219.0,
    veg: "false",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448039,
    catalogue_name: "Chicken Noodles",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448040,
    catalogue_name: "Chicken Garlic Noodles",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531447992,
    catalogue_name: "Chicken Hakka Noodles",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448028,
    catalogue_name: "Chicken Singapuri Noodles",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Noodles",
    subcategory_name: "Noodles",
    catalogue_id: 531448053,
    catalogue_name: "Chicken Chilli Noodles",
    full_price: 249.0,
    veg: "false",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561389947,
    catalogue_name: "Veg Basic wali Thali",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561389946,
    catalogue_name: "Veg Special wali Thali",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561392624,
    catalogue_name: "Mushroom wali Veg Special Thali",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Veg Indian Thali",
    catalogue_id: 561390680,
    catalogue_name: "Veg Badshaho wali Thali",
    full_price: 329.0,
    veg: "true",
  },
  {
    category_name: "Indian Thali",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561394704,
    catalogue_name: "Thali Basic Wali [Serves 1]",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561395025,
    catalogue_name: "Thali Special Wali",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Indian Thalis",
    subcategory_name: "Non Veg Indian Thali",
    catalogue_id: 561395400,
    catalogue_name: "Deluxe Thali",
    full_price: 379.0,
    veg: "false",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393412,
    catalogue_name: "Chinese Basic Thali",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393413,
    catalogue_name: "Chinese Special Thali",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thalis [Veg]",
    catalogue_id: 561393414,
    catalogue_name: "Chinese Deluxe Thali",
    full_price: 329.0,
    veg: "true",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394264,
    catalogue_name: "Basic Chinese Thali",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394265,
    catalogue_name: "Special Chinese Thali",
    full_price: 299.0,
    veg: "false",
  },
  {
    category_name: "Chinese Thalis",
    subcategory_name: "Chinese Thali [Non Veg]",
    catalogue_id: 561394424,
    catalogue_name: "Deluxe Chinese Thali",
    full_price: 349.0,
    veg: "false",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Veg Maggi",
    catalogue_id: 534225049,
    catalogue_name: "Vegetable Maggi",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Veg Maggi",
    catalogue_id: 534225065,
    catalogue_name: "Veg Cheese Maggi",
    full_price: 219.0,
    veg: "true",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Non Veg Maggi",
    catalogue_id: 534225692,
    catalogue_name: "Egg Maggi",
    full_price: 219.0,
    veg: "false",
  },
  {
    category_name: "Maggi",
    subcategory_name: "Non Veg Maggi",
    catalogue_id: 534225693,
    catalogue_name: "Chicken Maggi",
    full_price: 249.0,
    veg: "false",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448009,
    catalogue_name: "Paneer Chilli Gravy",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448021,
    catalogue_name: "Mushroom Chilli Gravy",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Veg Main Course",
    catalogue_id: 531448032,
    catalogue_name: "Veg Manchurian Gravy",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448023,
    catalogue_name: "Chicken Chilli Gravy",
    full_price: 269.0,
    veg: "false",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448013,
    catalogue_name: "Chicken 65 Gravy",
    full_price: 289.0,
    veg: "false",
  },
  {
    category_name: "Chinese Main Course",
    subcategory_name: "Non-Veg Main Course",
    catalogue_id: 531448025,
    catalogue_name: "Chicken Manchurian Gravy",
    full_price: 289.0,
    veg: "false",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315246,
    catalogue_name: "Aloo Matar",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315427,
    catalogue_name: "Aloo Gobhi",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315426,
    catalogue_name: "Mix Veg",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315037,
    catalogue_name: "Matar Mushroom",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 531448008,
    catalogue_name: "Paneer Kadhai Gravy",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 531448065,
    catalogue_name: "Paneer Butter Masala",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314940,
    catalogue_name: "Matar Paneer",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314941,
    catalogue_name: "Shahi Paneer",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550314942,
    catalogue_name: "Paneer Do Pyaza",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315035,
    catalogue_name: "Mushroom Butter Masala",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Indian Veg Main Course",
    catalogue_id: 550315036,
    catalogue_name: "Mushroom Masala Gravy",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531447998,
    catalogue_name: "Kadhai Chicken",
    full_price: 299.0,
    veg: "false",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531448022,
    catalogue_name: "Chicken Dehati",
    full_price: 299.0,
    veg: "false",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 531448061,
    catalogue_name: "Chicken Handi",
    full_price: 299.0,
    veg: "false",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 550314872,
    catalogue_name: "Chicken Do Pyaza",
    full_price: 349.0,
    veg: "false",
  },
  {
    category_name: "Indian Main Course",
    subcategory_name: "Non Veg Indian Main Course",
    catalogue_id: 550314873,
    catalogue_name: "Butter Chicken",
    full_price: 349.0,
    veg: "false",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448030,
    catalogue_name: "Veg Roll",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448055,
    catalogue_name: "Paneer 65 Roll",
    full_price: 229.0,
    veg: "true",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448069,
    catalogue_name: "Veg Manchurian Roll",
    full_price: 229.0,
    veg: "true",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448014,
    catalogue_name: "Egg Roll",
    full_price: 199.0,
    veg: "false",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448017,
    catalogue_name: "Chicken Roll",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448007,
    catalogue_name: "Chicken Egg Roll",
    full_price: 249.0,
    veg: "false",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531447994,
    catalogue_name: "Chicken 65 Roll",
    full_price: 249.0,
    veg: "false",
  },
  {
    category_name: "Rolls",
    subcategory_name: "Rolls",
    catalogue_id: 531448044,
    catalogue_name: "Chicken Manchurian Roll",
    full_price: 259.0,
    veg: "false",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531447997,
    catalogue_name: "Paneer Chilli Dry",
    full_price: 259.0,
    veg: "true",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448001,
    catalogue_name: "Paneer 65 Dry",
    full_price: 259.0,
    veg: "true",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448024,
    catalogue_name: "Manchurian Dry",
    full_price: 259.0,
    veg: "true",
  },
  {
    category_name: "Starters",
    subcategory_name: "Veg Starters",
    catalogue_id: 531448020,
    catalogue_name: "Mushroom Chilli Dry",
    full_price: 269.0,
    veg: "true",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531448012,
    catalogue_name: "Chicken 65 Dry",
    full_price: 269.0,
    veg: "false",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531448064,
    catalogue_name: "Chicken Chilli Dry",
    full_price: 269.0,
    veg: "false",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 531447999,
    catalogue_name: "Chicken Manchurian Dry",
    full_price: 279.0,
    veg: "false",
  },
  {
    category_name: "Starters",
    subcategory_name: "Non Veg Starters",
    catalogue_id: 538402178,
    catalogue_name: "Chicken Lollipop",
    full_price: 349.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531447991,
    catalogue_name: "Paneer Tikka Biryani",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448010,
    catalogue_name: "Veg Dum Biryani",
    full_price: 229.0,
    veg: "true",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448048,
    catalogue_name: "Veg Hyderabadi Biryani",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448066,
    catalogue_name: "Veg Lucknowi Biryani",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 532669375,
    catalogue_name: "Egg Biryani",
    full_price: 229.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448068,
    catalogue_name: "Chicken Biryani",
    full_price: 299.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448026,
    catalogue_name: "Chicken Tikka Dum Biryani",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448049,
    catalogue_name: "Chicken Hyderabadi Biryani",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 531448042,
    catalogue_name: "Chicken Lucknowi Biryani",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Biryani",
    subcategory_name: "Biryani",
    catalogue_id: 544320061,
    catalogue_name: "Chicken Leg Biryani [2 Leg Pieces]",
    full_price: 449.0,
    veg: "false",
  },
  

  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 5314480541,
    catalogue_name: "Veg Steamed Momos [4 Pieces]",
    full_price: 99.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 5314480542,
    catalogue_name: "Veg Steamed Momos [8 Pieces]",
    full_price: 149.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448029,
    catalogue_name: "Paneer Steamed Momos [4 Pieces]",
    full_price: 129.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448029,
    catalogue_name: "Paneer Steamed Momos [8 Pieces]",
    full_price: 149.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448045,
    catalogue_name: "Chicken Steamed Momos [4 Pieces]",
    full_price: 129.0,
    veg: "false",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448045,
    catalogue_name: "Chicken Steamed Momos [8 Pieces]",
    full_price: 149.0,
    veg: "false",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448043,
    catalogue_name: "Veg Fried Momos [4 Pieces]",
    full_price: 199.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448043,
    catalogue_name: "Veg Fried Momos [8 Pieces]",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531447993,
    catalogue_name: "Paneer Fried Momos",
    half_pieces: "4 Pieces",
    half_price: 199.0,
    full_pieces: "8 Pieces",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448004,
    catalogue_name: "Chicken Fried Momos",
    half_pieces: "4 Pieces",
    half_price: 219.0,
    full_pieces: "8 Pieces",
    full_price: 259.0,
    veg: "false",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448067,
    catalogue_name: "Veg Kurkuri Momos",
    half_pieces: "4 Pieces",
    half_price: 249.0,
    full_pieces: "8 Pieces",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448041,
    catalogue_name: "Paneer Kurkuri Momos",
    half_pieces: "4 Pieces",
    half_price: 249.0,
    full_pieces: "8 Pieces",
    full_price: 299.0,
    veg: "true",
  },
  {
    category_name: "Momos",
    subcategory_name: "Momos",
    catalogue_id: 531448006,
    catalogue_name: "Chicken Kurkuri Momos",
    half_pieces: "5 Pieces",
    half_price: 299.0,
    full_pieces: "10 Pieces",
    full_price: 349.0,
    veg: "false",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480560,
    catalogue_name: "Veg Noodles + Veg Manchurian",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480561,
    catalogue_name: "Chicken Noodles + Veg Manchurian",
    full_price: 279.0,
    veg: "false",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314480562,
    catalogue_name: "Chicken Noodles + Chicken Manchurian",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479950,
    catalogue_name: "Veg Fried Rice + Veg Manchurian",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479951,
    catalogue_name: "Chicken Fried Rice + Veg Manchurian",
    full_price: 279.0,
    veg: "false",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 5314479952,
    catalogue_name: "Chicken Fried Rice + Chicken Manchurian",
    full_price: 329.0,
    veg: "false",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 531448060,
    catalogue_name: "Biryani Combo",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Combos",
    subcategory_name: "Combos",
    catalogue_id: 531447996,
    catalogue_name: "Momos Combo",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Combos",
    subcategory_name: "Noodles Combo",
    catalogue_id: 531448016,
    catalogue_name: "Paneer Chilli",
    full_price: 249.0,
    veg: "true",
  },
  {
    category_name: "Combos",
    subcategory_name: "Noodles Combo",
    catalogue_id: 531448016,
    catalogue_name: "Chicken Chilli",
    full_price: 269.0,
    veg: "false",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892085,
    catalogue_name: "5 Tawa Roti",
    full_price: 85.0,
    veg: "true",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892086,
    catalogue_name: "2 Lachha Paratha",
    full_price: 80.0,
    veg: "true",
  },
  {
    category_name: "Breads",
    subcategory_name: "Breads",
    catalogue_id: 534892087,
    catalogue_name: "5 Tawa Roti with Butter",
    full_price: 110.0,
    veg: "true",
  },
  {
    category_name: "Rice",
    subcategory_name: "Rice",
    catalogue_id: 534226398,
    catalogue_name: "Plain Rice",
    full_price: 79.0,
    veg: "true",
  },
  {
    category_name: "Rice",
    subcategory_name: "Rice",
    catalogue_id: 534362609,
    catalogue_name: "Jeera Rice",
    full_price: 99.0,
    veg: "true",
  },
  {
    category_name: "Desserts",
    subcategory_name: "Desserts",
    catalogue_id: 544109219,
    catalogue_name: "Gulab Jamun (2 Pcs)",
    full_price: 100.0,
    veg: "true",
  },
];

export default data;
